---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Make sure the cloned project is absent to avoid problems with the git task
      file:
        path: /opt/AkkaKVStore
        state: absent










