---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  vars:
    maven_major: 3
    maven_version: 3.5.4
    maven_home_parent_directory: /opt
    maven_env_file: "/etc/profile.d/maven.sh"
    ansible_python_interpreter: /usr/bin/python3
    role: "{{ ansible_group }}"
    host_name: "{{ hostvars[inventory_hostname]['ansible_facts']['all_ipv4_addresses'] | sort | last }}"
  tasks:
    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    
    - block:
      - name: Download and Unarchive maven
        unarchive:
          src: "http://www.apache.org/dist/maven/maven-{{ maven_major }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
          dest: "{{maven_home_parent_directory}}"
          copy: no

      - name: Create maven symlink to /usr/bin
        file:
          src: "{{maven_home_parent_directory}}/apache-maven-{{maven_version}}/bin/mvn"
          dest: /usr/bin/mvn
          state: link

      - name: Configure maven and its environment variables
        lineinfile:
          dest: "~/.bashrc"
          line: "{{ item.line }}"
          create: yes
          state: present
        with_items:
          - { line: 'M2_HOME={{maven_home_parent_directory}}/apache-maven-{{maven_version}}' }
          - { line: 'PATH=$PATH:$M2_HOME/bin' }

    - name: Remove the project folder, if existing
      file:
        path: /opt/AkkaKVStore
        state: absent
        
    - name: Clone project from github      
      git: 
        repo: https://github.com/danilomo/AkkaKVStore.git
        dest: /opt/AkkaKVStore
        version: introducing_cluster_sharding

    - name: Install script to add IP tables entries
      template: src=templates/disconnect_from dest=/bin/disconnect_from
        
    - name: Install script to clean IP tables entries
      template: src=templates/connect_to dest=/bin/connect_to

    - name: Changing perm of /bin/connect_to, adding "+x"
      file: dest=/bin/connect_to mode=+x

    - name: Changing perm of /bin/disconnect_from, adding "+x"
      file: dest=/bin/disconnect_from mode=+x      
        
    - name: Copy frontend.conf to /src/resources/ folder
      template: src=templates/frontend.conf.j2 dest=/opt/AkkaKVStore/kvcluster/kvcluster-core/src/main/resources/frontend.conf

    - name: Copy backend.conf to /src/resources/ folder
      template: src=templates/backend.conf.j2 dest=/opt/AkkaKVStore/kvcluster/kvcluster-core/src/main/resources/backend.conf    

    - name: Copy client.conf to /src/resources/ folder
      template: src=templates/client.conf.j2 dest=/opt/AkkaKVStore/kvcluster/kvcluster-client/src/main/resources/client.conf 
    
    - name: Building project
      shell: "cd /opt/AkkaKVStore/kvcluster && mvn clean install -Dmaven.test.skip=true"
