---
- hosts: "{{ role }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Copy sbr-strategy.conf to /opt/AkkaKVStore/
      template: src=templates/{{ sbr_strategy }}.conf dest=/opt/AkkaKVStore/sbr-strategy.conf
    
    - name: Copy run_node.sh script to home folder
      template: src=templates/run_node.sh.j2 dest=~/run_node.sh
      
    - name: Changing perm of ~/run_node.sh, adding "+x"
      file: dest=~/run_node.sh mode=+x
      
    #- name: Run frontend nodes
    #  shell: ~/run_node.sh


      
