---
- hosts: "{{ group }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Changing perm of ~/run_node.sh, adding "+x"
      file: dest=~/run_node.sh mode=+x    
    - name: Run frontend nodes
      shell: ~/run_node.sh


      
