require './cluster_config'

VAGRANT_API_VERSION = "2"

cluster = Cluster.new()

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.ssh.forward_agent = true

  cluster.list_of_nodes.each do |node|
    (name, ip_address, role, last_node) = node
    cluster.groups[role] << name

    config.vm.define name do |box|
      box.vm.network :private_network, ip: ip_address
      
      box.vm.provider :virtualbox do |vb|
        cluster.configure_virtualbox_vm(vb, name)      
      end
      
      cluster.apply_specific_config(name, box)       

      if last_node
        box.vm.provision "ansible" do |ansible|
          ansible.limit = 'all'
          ansible.playbook = "setup_nodes.yml"
          ansible.extra_vars = { seed_nodes: cluster.seed_nodes }
          ansible.groups = cluster.groups
        end        
      end
    end    
  end
end

